// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class LeaderBoardsIds
{
        public const string leaderboard_puntuaciones = "CgkIyvq_k-gbEAIQAA"; // <GPGSID>
        public const string leaderboard_total_de_muertes = "CgkIyvq_k-gbEAIQAQ"; // <GPGSID>
        public const string leaderboard_altura_alcanzada = "CgkIyvq_k-gbEAIQBA"; // <GPGSID>
        public const string leaderboard_tiempo_de_juego = "CgkIyvq_k-gbEAIQAg"; // <GPGSID>
        public const string leaderboard_frutas_recolectadas = "CgkIyvq_k-gbEAIQAw"; // <GPGSID>

}

